#+TITLE:       Install anaconda-mode in emacs
#+AUTHOR:
#+EMAIL:       robin.chenyu@gmail.com
#+DATE:        2017-02-16 周四
#+URI:         /blog/%y/%m/%d/install-anaconda-mode-in-emacs
#+KEYWORDS:    emacs, python, anaconda-mode
#+TAGS:        emacs, python, anaconda-mode
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: 安装配置anaconda-mode

** 配置anaconda-mode
   Python配置使用的purcell的python配置，如下:
   #+BEGIN_SRC emacs-lisp
(when (maybe-require-package 'anaconda-mode)
  (after-load 'python
    (add-hook 'python-mode-hook 'anaconda-mode)
    (add-hook 'python-mode-hook 'anaconda-eldoc-mode)))

   #+END_SRC

** 存在问题
   在编辑python代码时, =anaconda-mode= 无法正常工作，出现如下错误:
   #+BEGIN_SRC log
Skipping development or system egg: anaconda-mode 0.1.7
Reading https://pypi.python.org/simple/anaconda_mode/
Download error on https://pypi.python.org/simple/anaconda_mode/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645) -- Some packages may not be found!
Reading https://pypi.python.org/simple/anaconda-mode/
Download error on https://pypi.python.org/simple/anaconda-mode/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645) -- Some packages may not be found!
Couldn't retrieve index page for 'anaconda_mode'
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645) -- Some packages may not be found!
No local packages or working download links found for anaconda_mode==0.1.7
error: Could not find suitable distribution for Requirement.parse('anaconda_mode==0.1.7') (--always-copy skips system and development eggs)
   #+END_SRC

** 检查方法
   我系统使用的python3, 把系统变量 ~python-shell-interpreter~ 修改为 python3
   然后安装 ~anaconda-mode~ , ~pip install anaconda_mode~
   重启emacs,错误依然存在。

** 调试检查
   没有办法，查看anaconda-mode.el代码，发现主要是在安装检查时运行代码段。
   #+BEGIN_SRC emacs-lisp
(defvar anaconda-mode-check-installation-command "
import sys, os, site
from pkg_resources import find_distributions
directory = os.path.expanduser(sys.argv[-1])
site.addsitedir(directory)
candidates = [ directory ]
candidates.extend(map(lambda subdir: os.path.join(directory, subdir),
                      os.listdir(directory)))
location = None
for path_item in candidates:
    for dist in find_distributions(path_item, only=True):
        if dist.project_name == 'anaconda-mode':
            location = path_item
            break
    if location:
        break
else:
    # IPython patch sys.exit, so we can't use it.
    os._exit(1)
# Check if the detected location was added properly to sys.path.
# This is required for egg-based installation to work correctly.
for path_item in sys.path:
    if os.path.abspath(path_item) == os.path.abspath(location):
        break
else:
    os._exit(1)
" "Check if `anaconda-mode' server is installed or not.")
   #+END_SRC

   上面这段代码主要检查sys.argv[-1]传入文件夹是否安装有anaconda-mode，查找调用处
   #+BEGIN_SRC emacs-lisp
(defun anaconda-mode-check (&optional callback)
  "Check `anaconda-mode' server installation.
CALLBACK function will be called when `anaconda-mode-port' will
be bound."
  (setq anaconda-mode-process
        (start-pythonic :process anaconda-mode-process-name
                        :buffer anaconda-mode-process-buffer
                        :sentinel (lambda (process event) (anaconda-mode-check-sentinel process event callback))
                        :args (list "-c"
                                    anaconda-mode-check-installation-command
                                    (anaconda-mode-server-directory)))))

(defun anaconda-mode-server-directory ()
  "Anaconda mode installation directory."
  (f-short (f-join anaconda-mode-installation-directory
                   anaconda-mode-server-version)))
   #+END_SRC
   发现检查的 ~anaconda-mode~ 安装的文件夹位于 ="~/.emacs.d/anaconda-mode/0.1.7"= ，
   检查这个文件夹为空的。于是配置变量 ~anaconda-mode-installation-directory~ 为系统
   ~anaconda-mode~ 的安装文件夹 =c:/msys64/mingw64/lib/python3.5/site-packages= ,

   重启emacs测试，发现还是报相同错误，再次检查，发现代码检查的目录跑到 =c:/msys64/mingw64/lib/python3.5/site-packages/0.1.7= 文件夹下了。
   使用笨方法，把系统安装的 =c:/msys64/mingw64/lib/python3.5/site-packages/anaconda-mode.py= 和
   =c:/msys64/mingw64/lib/python3.5/site-packages/anaconda_mode-0.1.7.dist-info= 目录拷贝到
   =~/.emacs.d/anaconda-mode/0.1.7= ，再次重启emacs, 运行正常。
   在 =*anaconda-mode*= buffer中出现 ~anaconda_mode port 50248~, 表示anaconda-mode正常运行起来啦~
