#+TITLE:       setup org-page
#+AUTHOR:      ChenYu
#+EMAIL:       robin.chenyu@gmail.com
#+DATE:        2017-01-30 Mon
#+URI:         /blog/%y/%m/%d/setup-org-page
#+KEYWORDS:    emacs, org-page, github
#+TAGS:        emacs, org-page, github
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: Setup org-page and publish to github page

** Install Org-Page
   First need to delete org package, or it would conflict with new versions,
then install *org-plus-contrib*. Could be install by elpa package.

** Setup init.el file
   #+BEGIN_SRC elisp
(require 'org-page)
(setq op/repository-directory "~/pp")
(setq op/site-domain "http://blog912.cn")
(setq op/personal-github-link "https://github.com/robinchenyu")
(setq op/site-main-title "The Blog")
(setq op/site-sub-title "Emacs, Programming")
;; (setq op/personal-disqus-shortname "theblog")
   #+END_SRC

** Create a new repository by op/new-repository
   Create a new reporsitory, then add github page rep to it.
   #+BEGIN_SRC
   M-x op/new-repository RET
   #+END_SRC
   #+BEGIN_SRC bash
   cd /path/to/rep
   git remote add origin git@github.com:robinchenyu/robinchenyu.github.io
   git checkout source
   git branch --set-upstream-to=origin/source source
   # then merge with github page files

   git checkout master
   git branch --set-upstream-to=origin/master master
   #+END_SRC

** Write a new post with op/new-post
   #+BEGIN_SRC
   M-x op/new-post RET
   #+END_SRC

** Publish the post with op/do-publication
   #+BEGIN_SRC
   M-x op/do-publication
   #+END_SRC

   some questions need to answer.
   1. Publish all org-files (y or n) y
   2. Publish to directory? (original repo if not) (y or n) n
   3. Auto-commit to repo? (y or n) y
   4. Auto-push to repo? (y or n) y
** 修复RSS pubDate乱码问题
   检查到是=op/update-rss=函数中如下部分返回代码
   #+BEGIN_SRC elisp
   (format-time-string "%a, %d %b %Y %T %Z")
   #+END_SRC

   把`%Z`替换为`%z`修复问题
** 修改theme
   修改为emacs_love后，发现没有代码高亮了，需要做如下修改。
   1. 先拷贝出org-page中自带的themes
      拷贝出来在做修改，这样在包升级后，不会被覆盖修改。
      #+BEGIN_SRC bash
      cp ~/.emacs.d/elpa/org-page-20161121.2129/themes ~/.emacs.d/themes
      #+END_SRC
   2. 修改themes路径
      #+BEGIN_SRC elisp
(setq op/theme 'emacs_love)
(setq op/theme-root-directory "c:/msys64/home/chenyu/.emacs.d/themes/")
      #+END_SRC
   3. 修改模板，添加代码高亮支持
      在.emacs.d/themes/emacs_love/templates/header.mustache添加下面的第二行:
      #+BEGIN_SRC html
  <link rel="stylesheet" href="/media/css/kdComment.css" type="text/css">
  <link rel="stylesheet" href="/media/css/prettify.css" type="text/css">
      #+END_SRC
      在.emacs.d/themes/emacs_love/templates/footer.mustache添加下面的第二行:
      #+BEGIN_SRC html
  <script src="/media/js/jquery-2.1.3.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/prettify/r298/prettify.js"></script>
      #+END_SRC
